tableA_path: data/raw/tableA.csv
tableB_path: data/raw/tableB.csv

processed_dir: data/processed
models_dir: models
outputs_dir: outputs/runs

div_distcd: [1202, 1212, 1222, 1232, 1242, 1252, 1262, 1272]

H_label: 10
H_eval: 20

topk_list: [20, 50, 100]
threshold: 0.7764
cooldown_td: 10

start_all: "2010-01-01"
end_all: "2024-12-31"

split:
  train_start: "2010-01-01"
  train_end:   "2021-12-31"
  val_start:   "2022-01-01"
  val_end:     "2022-12-31"
  test_start:  "2023-01-01"
  test_end:    "2024-12-31"

embargo_td: 10
